### ISSUE TITLE
Can you provide an example of this in use?

### ISSUE THREAD

**Issue by camiolo** [microsoft/connected-workbooks#27]
Specifically, I've made a file showing how to get started with PQ.  I'd love to add in your features, but I don't understand how to use them.

https://github.com/camiolo/Power_Query/blob/main/Power%20Query%20Template.xltx

**Comment by ron-b** [comment]
Hey @camiolo , this library isn't intended for use within Excel, its meant to be use by other application developers, allowing them to add "Open in Excel" capabilities, basically a button that can generate a workbook already connected to a data source via PQ.

Hope this clarifies it, let me know if you have further questions.
